export declare const addButton: string;
export declare const addButtonField: string;
export declare const addMenu: string;
export declare const addMenuList: string;
export declare const menuOption: string;
export declare const menuOptionText: string;
export declare const nodeWindowTitle: string;
export declare const searchBar: string;
export declare const selectedMenuOption: string;
